export { default as Dashboard } from './Dashboard';
export { LoginForm } from './LoginForm';
export { JobsSection } from './Sections/JobsSection';
export { AdmissionsSection } from './Sections/AdmissionsSection';
export { ResultsSection } from './Sections/ResultsSection';
export { AdmitCardsSection } from './Sections/AdmitCardsSection';
export { AnswerKeysSection } from './Sections/AnswerKeysSection';
export { SyllabusSection } from './Sections/SyllabusSection';
export { DocumentsSection } from './Sections/DocumentsSection';
export { ResourcesSection } from './Sections/ResourcesSection';
export { SchemesSection } from './Sections/SchemesSection';
export { authService } from './authService';
export * from './schemas';